SET IDENTITY_INSERT [dbo].[Confederacion] ON
INSERT INTO [dbo].[Confederacion] (idConfederacion, idDeporte, nombre, estado) VALUES (1, 98, 'FIFA', 'I');
INSERT INTO [dbo].[Confederacion] (idConfederacion, idDeporte, nombre, estado) VALUES (2, 98, 'CONMEBOL', 'I');
INSERT INTO [dbo].[Confederacion] (idConfederacion, idDeporte, nombre, estado) VALUES (3, 98, 'UEFA', 'I');
INSERT INTO [dbo].[Confederacion] (idConfederacion, idDeporte, nombre, estado) VALUES (4, 98, 'CONCACAF', 'I');
INSERT INTO [dbo].[Confederacion] (idConfederacion, idDeporte, nombre, estado) VALUES (5, 110, 'FIFA Women', 'I');
INSERT INTO [dbo].[Confederacion] (idConfederacion, idDeporte, nombre, estado) VALUES (6, 110, 'UEFA Women', 'I');
INSERT INTO [dbo].[Confederacion] (idConfederacion, idDeporte, nombre, estado) VALUES (7, 99, 'FIBA', 'I');
INSERT INTO [dbo].[Confederacion] (idConfederacion, idDeporte, nombre, estado) VALUES (8, 99, 'FIBA Américas', 'I');
INSERT INTO [dbo].[Confederacion] (idConfederacion, idDeporte, nombre, estado) VALUES (9, 111, 'FIBA Women', 'I');
INSERT INTO [dbo].[Confederacion] (idConfederacion, idDeporte, nombre, estado) VALUES (10, 100, 'ATP', 'I');
INSERT INTO [dbo].[Confederacion] (idConfederacion, idDeporte, nombre, estado) VALUES (11, 100, 'ITF', 'I');
INSERT INTO [dbo].[Confederacion] (idConfederacion, idDeporte, nombre, estado) VALUES (12, 112, 'WTA', 'I');
INSERT INTO [dbo].[Confederacion] (idConfederacion, idDeporte, nombre, estado) VALUES (13, 101, 'WBSC', 'I');
INSERT INTO [dbo].[Confederacion] (idConfederacion, idDeporte, nombre, estado) VALUES (14, 101, 'COPABE', 'I');
INSERT INTO [dbo].[Confederacion] (idConfederacion, idDeporte, nombre, estado) VALUES (15, 113, 'WBSC Softball', 'I');
INSERT INTO [dbo].[Confederacion] (idConfederacion, idDeporte, nombre, estado) VALUES (16, 102, 'World Rugby', 'I');
INSERT INTO [dbo].[Confederacion] (idConfederacion, idDeporte, nombre, estado) VALUES (17, 102, 'Sudamérica Rugby', 'I');
INSERT INTO [dbo].[Confederacion] (idConfederacion, idDeporte, nombre, estado) VALUES (18, 114, 'World Rugby Women', 'I');
INSERT INTO [dbo].[Confederacion] (idConfederacion, idDeporte, nombre, estado) VALUES (19, 103, 'FIVB', 'I');
INSERT INTO [dbo].[Confederacion] (idConfederacion, idDeporte, nombre, estado) VALUES (20, 103, 'CSV', 'I');
INSERT INTO [dbo].[Confederacion] (idConfederacion, idDeporte, nombre, estado) VALUES (21, 115, 'FIVB Women', 'I');
INSERT INTO [dbo].[Confederacion] (idConfederacion, idDeporte, nombre, estado) VALUES (22, 104, 'WBA', 'I');
INSERT INTO [dbo].[Confederacion] (idConfederacion, idDeporte, nombre, estado) VALUES (23, 104, 'WBC', 'I');
INSERT INTO [dbo].[Confederacion] (idConfederacion, idDeporte, nombre, estado) VALUES (24, 116, 'WBC Female', 'I');
INSERT INTO [dbo].[Confederacion] (idConfederacion, idDeporte, nombre, estado) VALUES (25, 105, 'UCI', 'I');
INSERT INTO [dbo].[Confederacion] (idConfederacion, idDeporte, nombre, estado) VALUES (26, 105, 'COPACI', 'I');
INSERT INTO [dbo].[Confederacion] (idConfederacion, idDeporte, nombre, estado) VALUES (27, 117, 'UCI Women', 'I');
INSERT INTO [dbo].[Confederacion] (idConfederacion, idDeporte, nombre, estado) VALUES (28, 106, 'World Aquatics (FINA)', 'I');
INSERT INTO [dbo].[Confederacion] (idConfederacion, idDeporte, nombre, estado) VALUES (29, 118, 'World Aquatics Women', 'I');
INSERT INTO [dbo].[Confederacion] (idConfederacion, idDeporte, nombre, estado) VALUES (30, 107, 'World Athletics', 'I');
INSERT INTO [dbo].[Confederacion] (idConfederacion, idDeporte, nombre, estado) VALUES (31, 119, 'World Athletics Women', 'I');
INSERT INTO [dbo].[Confederacion] (idConfederacion, idDeporte, nombre, estado) VALUES (32, 108, 'IGF', 'I');
INSERT INTO [dbo].[Confederacion] (idConfederacion, idDeporte, nombre, estado) VALUES (33, 108, 'PGA Tour', 'I');
INSERT INTO [dbo].[Confederacion] (idConfederacion, idDeporte, nombre, estado) VALUES (34, 120, 'LPGA', 'I');
INSERT INTO [dbo].[Confederacion] (idConfederacion, idDeporte, nombre, estado) VALUES (35, 109, 'LEN', 'I');
INSERT INTO [dbo].[Confederacion] (idConfederacion, idDeporte, nombre, estado) VALUES (36, 121, 'FIG', 'I');
INSERT INTO [dbo].[Confederacion] (idConfederacion, idDeporte, nombre, estado) VALUES (37, 121, 'UPAG', 'I');
INSERT INTO [dbo].[Confederacion] (idConfederacion, idDeporte, nombre, estado) VALUES (38, 98, 'FIFA', 'I');
INSERT INTO [dbo].[Confederacion] (idConfederacion, idDeporte, nombre, estado) VALUES (39, 98, 'CONMEBOL', 'I');
INSERT INTO [dbo].[Confederacion] (idConfederacion, idDeporte, nombre, estado) VALUES (40, 98, 'UEFA', 'I');
INSERT INTO [dbo].[Confederacion] (idConfederacion, idDeporte, nombre, estado) VALUES (41, 98, 'CONCACAF', 'I');
INSERT INTO [dbo].[Confederacion] (idConfederacion, idDeporte, nombre, estado) VALUES (42, 110, 'FIFA Women', 'I');
INSERT INTO [dbo].[Confederacion] (idConfederacion, idDeporte, nombre, estado) VALUES (43, 110, 'UEFA Women', 'I');
INSERT INTO [dbo].[Confederacion] (idConfederacion, idDeporte, nombre, estado) VALUES (44, 99, 'FIBA', 'I');
INSERT INTO [dbo].[Confederacion] (idConfederacion, idDeporte, nombre, estado) VALUES (45, 99, 'FIBA Américas', 'I');
INSERT INTO [dbo].[Confederacion] (idConfederacion, idDeporte, nombre, estado) VALUES (46, 111, 'FIBA Women', 'I');
INSERT INTO [dbo].[Confederacion] (idConfederacion, idDeporte, nombre, estado) VALUES (47, 100, 'ATP', 'I');
INSERT INTO [dbo].[Confederacion] (idConfederacion, idDeporte, nombre, estado) VALUES (48, 100, 'ITF', 'I');
INSERT INTO [dbo].[Confederacion] (idConfederacion, idDeporte, nombre, estado) VALUES (49, 112, 'WTA', 'I');
INSERT INTO [dbo].[Confederacion] (idConfederacion, idDeporte, nombre, estado) VALUES (50, 101, 'WBSC', 'I');
INSERT INTO [dbo].[Confederacion] (idConfederacion, idDeporte, nombre, estado) VALUES (51, 101, 'COPABE', 'I');
INSERT INTO [dbo].[Confederacion] (idConfederacion, idDeporte, nombre, estado) VALUES (52, 113, 'WBSC Softball', 'I');
INSERT INTO [dbo].[Confederacion] (idConfederacion, idDeporte, nombre, estado) VALUES (53, 102, 'World Rugby', 'I');
INSERT INTO [dbo].[Confederacion] (idConfederacion, idDeporte, nombre, estado) VALUES (54, 102, 'Sudamérica Rugby', 'I');
INSERT INTO [dbo].[Confederacion] (idConfederacion, idDeporte, nombre, estado) VALUES (55, 114, 'World Rugby Women', 'I');
INSERT INTO [dbo].[Confederacion] (idConfederacion, idDeporte, nombre, estado) VALUES (56, 103, 'FIVB', 'I');
INSERT INTO [dbo].[Confederacion] (idConfederacion, idDeporte, nombre, estado) VALUES (57, 103, 'CSV', 'I');
INSERT INTO [dbo].[Confederacion] (idConfederacion, idDeporte, nombre, estado) VALUES (58, 115, 'FIVB Women', 'I');
INSERT INTO [dbo].[Confederacion] (idConfederacion, idDeporte, nombre, estado) VALUES (59, 104, 'WBA', 'I');
INSERT INTO [dbo].[Confederacion] (idConfederacion, idDeporte, nombre, estado) VALUES (60, 104, 'WBC', 'I');
INSERT INTO [dbo].[Confederacion] (idConfederacion, idDeporte, nombre, estado) VALUES (61, 116, 'WBC Female', 'I');
INSERT INTO [dbo].[Confederacion] (idConfederacion, idDeporte, nombre, estado) VALUES (62, 105, 'UCI', 'I');
INSERT INTO [dbo].[Confederacion] (idConfederacion, idDeporte, nombre, estado) VALUES (63, 105, 'COPACI', 'I');
INSERT INTO [dbo].[Confederacion] (idConfederacion, idDeporte, nombre, estado) VALUES (64, 117, 'UCI Women', 'I');
INSERT INTO [dbo].[Confederacion] (idConfederacion, idDeporte, nombre, estado) VALUES (65, 106, 'World Aquatics (FINA)', 'I');
INSERT INTO [dbo].[Confederacion] (idConfederacion, idDeporte, nombre, estado) VALUES (66, 118, 'World Aquatics Women', 'I');
INSERT INTO [dbo].[Confederacion] (idConfederacion, idDeporte, nombre, estado) VALUES (67, 107, 'World Athletics', 'I');
INSERT INTO [dbo].[Confederacion] (idConfederacion, idDeporte, nombre, estado) VALUES (68, 119, 'World Athletics Women', 'I');
INSERT INTO [dbo].[Confederacion] (idConfederacion, idDeporte, nombre, estado) VALUES (69, 108, 'IGF', 'I');
INSERT INTO [dbo].[Confederacion] (idConfederacion, idDeporte, nombre, estado) VALUES (70, 108, 'PGA Tour', 'I');
INSERT INTO [dbo].[Confederacion] (idConfederacion, idDeporte, nombre, estado) VALUES (71, 120, 'LPGA', 'I');
INSERT INTO [dbo].[Confederacion] (idConfederacion, idDeporte, nombre, estado) VALUES (72, 109, 'LEN', 'I');
INSERT INTO [dbo].[Confederacion] (idConfederacion, idDeporte, nombre, estado) VALUES (73, 121, 'FIG', 'I');
INSERT INTO [dbo].[Confederacion] (idConfederacion, idDeporte, nombre, estado) VALUES (74, 121, 'UPAG', 'I');
INSERT INTO [dbo].[Confederacion] (idConfederacion, idDeporte, nombre, estado) VALUES (75, 98, 'FIFA', 'A');
INSERT INTO [dbo].[Confederacion] (idConfederacion, idDeporte, nombre, estado) VALUES (76, 98, 'CONMEBOL', 'A');
INSERT INTO [dbo].[Confederacion] (idConfederacion, idDeporte, nombre, estado) VALUES (77, 98, 'UEFA', 'A');
INSERT INTO [dbo].[Confederacion] (idConfederacion, idDeporte, nombre, estado) VALUES (78, 98, 'CONCACAF', 'A');
INSERT INTO [dbo].[Confederacion] (idConfederacion, idDeporte, nombre, estado) VALUES (79, 110, 'FIFA Women', 'A');
INSERT INTO [dbo].[Confederacion] (idConfederacion, idDeporte, nombre, estado) VALUES (80, 110, 'UEFA Women', 'A');
INSERT INTO [dbo].[Confederacion] (idConfederacion, idDeporte, nombre, estado) VALUES (81, 99, 'FIBA', 'A');
INSERT INTO [dbo].[Confederacion] (idConfederacion, idDeporte, nombre, estado) VALUES (82, 99, 'FIBA Américas', 'A');
INSERT INTO [dbo].[Confederacion] (idConfederacion, idDeporte, nombre, estado) VALUES (83, 111, 'FIBA Women', 'A');
INSERT INTO [dbo].[Confederacion] (idConfederacion, idDeporte, nombre, estado) VALUES (84, 100, 'ATP', 'A');
INSERT INTO [dbo].[Confederacion] (idConfederacion, idDeporte, nombre, estado) VALUES (85, 100, 'ITF', 'A');
INSERT INTO [dbo].[Confederacion] (idConfederacion, idDeporte, nombre, estado) VALUES (86, 112, 'WTA', 'A');
INSERT INTO [dbo].[Confederacion] (idConfederacion, idDeporte, nombre, estado) VALUES (87, 101, 'WBSC', 'A');
INSERT INTO [dbo].[Confederacion] (idConfederacion, idDeporte, nombre, estado) VALUES (88, 101, 'COPABE', 'A');
INSERT INTO [dbo].[Confederacion] (idConfederacion, idDeporte, nombre, estado) VALUES (89, 113, 'WBSC Softball', 'A');
INSERT INTO [dbo].[Confederacion] (idConfederacion, idDeporte, nombre, estado) VALUES (90, 102, 'World Rugby', 'A');
INSERT INTO [dbo].[Confederacion] (idConfederacion, idDeporte, nombre, estado) VALUES (91, 102, 'Sudamérica Rugby', 'A');
INSERT INTO [dbo].[Confederacion] (idConfederacion, idDeporte, nombre, estado) VALUES (92, 114, 'World Rugby Women', 'A');
INSERT INTO [dbo].[Confederacion] (idConfederacion, idDeporte, nombre, estado) VALUES (93, 103, 'FIVB', 'A');
INSERT INTO [dbo].[Confederacion] (idConfederacion, idDeporte, nombre, estado) VALUES (94, 103, 'CSV', 'A');
INSERT INTO [dbo].[Confederacion] (idConfederacion, idDeporte, nombre, estado) VALUES (95, 115, 'FIVB Women', 'A');
INSERT INTO [dbo].[Confederacion] (idConfederacion, idDeporte, nombre, estado) VALUES (96, 104, 'WBA', 'A');
INSERT INTO [dbo].[Confederacion] (idConfederacion, idDeporte, nombre, estado) VALUES (97, 104, 'WBC', 'A');
INSERT INTO [dbo].[Confederacion] (idConfederacion, idDeporte, nombre, estado) VALUES (98, 116, 'WBC Female', 'A');
INSERT INTO [dbo].[Confederacion] (idConfederacion, idDeporte, nombre, estado) VALUES (99, 105, 'UCI', 'A');
INSERT INTO [dbo].[Confederacion] (idConfederacion, idDeporte, nombre, estado) VALUES (100, 105, 'COPACI', 'A');
INSERT INTO [dbo].[Confederacion] (idConfederacion, idDeporte, nombre, estado) VALUES (101, 117, 'UCI Women', 'A');
INSERT INTO [dbo].[Confederacion] (idConfederacion, idDeporte, nombre, estado) VALUES (102, 106, 'World Aquatics (FINA)', 'A');
INSERT INTO [dbo].[Confederacion] (idConfederacion, idDeporte, nombre, estado) VALUES (103, 118, 'World Aquatics Women', 'A');
INSERT INTO [dbo].[Confederacion] (idConfederacion, idDeporte, nombre, estado) VALUES (104, 107, 'World Athletics', 'A');
INSERT INTO [dbo].[Confederacion] (idConfederacion, idDeporte, nombre, estado) VALUES (105, 119, 'World Athletics Women', 'A');
INSERT INTO [dbo].[Confederacion] (idConfederacion, idDeporte, nombre, estado) VALUES (106, 108, 'IGF', 'A');
INSERT INTO [dbo].[Confederacion] (idConfederacion, idDeporte, nombre, estado) VALUES (107, 108, 'PGA Tour', 'A');
INSERT INTO [dbo].[Confederacion] (idConfederacion, idDeporte, nombre, estado) VALUES (108, 120, 'LPGA', 'A');
INSERT INTO [dbo].[Confederacion] (idConfederacion, idDeporte, nombre, estado) VALUES (109, 109, 'LEN', 'A');
INSERT INTO [dbo].[Confederacion] (idConfederacion, idDeporte, nombre, estado) VALUES (110, 121, 'FIG', 'A');
INSERT INTO [dbo].[Confederacion] (idConfederacion, idDeporte, nombre, estado) VALUES (111, 121, 'UPAG', 'A');
SET IDENTITY_INSERT [dbo].[Confederacion] OFF
GO

SET IDENTITY_INSERT [dbo].[Deporte] ON
INSERT INTO [dbo].[Deporte] (idDeporte, nombre, idGenero, estado) VALUES (98, 'Fútbol Masculino', 1005, 'A');
INSERT INTO [dbo].[Deporte] (idDeporte, nombre, idGenero, estado) VALUES (99, 'Baloncesto Masculino', 1005, 'A');
INSERT INTO [dbo].[Deporte] (idDeporte, nombre, idGenero, estado) VALUES (100, 'Tenis Masculino', 1005, 'A');
INSERT INTO [dbo].[Deporte] (idDeporte, nombre, idGenero, estado) VALUES (101, 'Béisbol Masculino', 1005, 'A');
INSERT INTO [dbo].[Deporte] (idDeporte, nombre, idGenero, estado) VALUES (102, 'Rugby Masculino', 1005, 'A');
INSERT INTO [dbo].[Deporte] (idDeporte, nombre, idGenero, estado) VALUES (103, 'Voleibol Masculino', 1005, 'A');
INSERT INTO [dbo].[Deporte] (idDeporte, nombre, idGenero, estado) VALUES (104, 'Boxeo Masculino', 1005, 'A');
INSERT INTO [dbo].[Deporte] (idDeporte, nombre, idGenero, estado) VALUES (105, 'Ciclismo Masculino', 1005, 'A');
INSERT INTO [dbo].[Deporte] (idDeporte, nombre, idGenero, estado) VALUES (106, 'Natación Masculina', 1005, 'A');
INSERT INTO [dbo].[Deporte] (idDeporte, nombre, idGenero, estado) VALUES (107, 'Atletismo Masculino', 1005, 'A');
INSERT INTO [dbo].[Deporte] (idDeporte, nombre, idGenero, estado) VALUES (108, 'Golf Masculino', 1005, 'A');
INSERT INTO [dbo].[Deporte] (idDeporte, nombre, idGenero, estado) VALUES (109, 'Waterpolo Masculino', 1005, 'A');
INSERT INTO [dbo].[Deporte] (idDeporte, nombre, idGenero, estado) VALUES (110, 'Fútbol Femenino', 1006, 'A');
INSERT INTO [dbo].[Deporte] (idDeporte, nombre, idGenero, estado) VALUES (111, 'Baloncesto Femenino', 1006, 'A');
INSERT INTO [dbo].[Deporte] (idDeporte, nombre, idGenero, estado) VALUES (112, 'Tenis Femenino', 1006, 'A');
INSERT INTO [dbo].[Deporte] (idDeporte, nombre, idGenero, estado) VALUES (113, 'Sóftbol Femenino', 1006, 'A');
INSERT INTO [dbo].[Deporte] (idDeporte, nombre, idGenero, estado) VALUES (114, 'Rugby Femenino', 1006, 'A');
INSERT INTO [dbo].[Deporte] (idDeporte, nombre, idGenero, estado) VALUES (115, 'Voleibol Femenino', 1006, 'A');
INSERT INTO [dbo].[Deporte] (idDeporte, nombre, idGenero, estado) VALUES (116, 'Boxeo Femenino', 1006, 'A');
INSERT INTO [dbo].[Deporte] (idDeporte, nombre, idGenero, estado) VALUES (117, 'Ciclismo Femenino', 1006, 'A');
INSERT INTO [dbo].[Deporte] (idDeporte, nombre, idGenero, estado) VALUES (118, 'Natación Femenina', 1006, 'A');
INSERT INTO [dbo].[Deporte] (idDeporte, nombre, idGenero, estado) VALUES (119, 'Atletismo Femenino', 1006, 'A');
INSERT INTO [dbo].[Deporte] (idDeporte, nombre, idGenero, estado) VALUES (120, 'Golf Femenino', 1006, 'A');
INSERT INTO [dbo].[Deporte] (idDeporte, nombre, idGenero, estado) VALUES (121, 'Gimnasia Rítmica', 1006, 'A');
SET IDENTITY_INSERT [dbo].[Deporte] OFF
GO

SET IDENTITY_INSERT [dbo].[Division] ON
INSERT INTO [dbo].[Division] (idDivision, nombre, idDeporte, estado) VALUES (2, 'Primera División', 98, 'I');
INSERT INTO [dbo].[Division] (idDivision, nombre, idDeporte, estado) VALUES (3, 'Segunda División', 98, 'I');
INSERT INTO [dbo].[Division] (idDivision, nombre, idDeporte, estado) VALUES (4, 'Tercera División', 98, 'I');
INSERT INTO [dbo].[Division] (idDivision, nombre, idDeporte, estado) VALUES (5, 'Liga Nacional', 99, 'I');
INSERT INTO [dbo].[Division] (idDivision, nombre, idDeporte, estado) VALUES (6, 'Liga de Ascenso', 99, 'I');
INSERT INTO [dbo].[Division] (idDivision, nombre, idDeporte, estado) VALUES (7, 'Categoría A (Pro)', 100, 'I');
INSERT INTO [dbo].[Division] (idDivision, nombre, idDeporte, estado) VALUES (8, 'Categoría B (Amateur)', 100, 'I');
INSERT INTO [dbo].[Division] (idDivision, nombre, idDeporte, estado) VALUES (9, 'Liga Mayor', 101, 'I');
INSERT INTO [dbo].[Division] (idDivision, nombre, idDeporte, estado) VALUES (10, 'Liga Menor', 101, 'I');
INSERT INTO [dbo].[Division] (idDivision, nombre, idDeporte, estado) VALUES (11, 'División de Honor', 102, 'I');
INSERT INTO [dbo].[Division] (idDivision, nombre, idDeporte, estado) VALUES (12, 'Pre-Intermedia', 102, 'I');
INSERT INTO [dbo].[Division] (idDivision, nombre, idDeporte, estado) VALUES (13, 'Serie A1', 103, 'I');
INSERT INTO [dbo].[Division] (idDivision, nombre, idDeporte, estado) VALUES (14, 'Serie A2', 103, 'I');
INSERT INTO [dbo].[Division] (idDivision, nombre, idDeporte, estado) VALUES (15, 'Categoría Profesional', 104, 'I');
INSERT INTO [dbo].[Division] (idDivision, nombre, idDeporte, estado) VALUES (16, 'Categoría Amateur', 104, 'I');
INSERT INTO [dbo].[Division] (idDivision, nombre, idDeporte, estado) VALUES (17, 'Elite', 105, 'I');
INSERT INTO [dbo].[Division] (idDivision, nombre, idDeporte, estado) VALUES (18, 'Sub-23', 105, 'I');
INSERT INTO [dbo].[Division] (idDivision, nombre, idDeporte, estado) VALUES (19, 'División Nacional', 106, 'I');
INSERT INTO [dbo].[Division] (idDivision, nombre, idDeporte, estado) VALUES (20, 'Federados', 107, 'I');
INSERT INTO [dbo].[Division] (idDivision, nombre, idDeporte, estado) VALUES (21, 'Scratch', 108, 'I');
INSERT INTO [dbo].[Division] (idDivision, nombre, idDeporte, estado) VALUES (22, 'Handicap Alto', 108, 'I');
INSERT INTO [dbo].[Division] (idDivision, nombre, idDeporte, estado) VALUES (23, 'Primera Categoría', 109, 'I');
INSERT INTO [dbo].[Division] (idDivision, nombre, idDeporte, estado) VALUES (24, 'Primera División', 110, 'I');
INSERT INTO [dbo].[Division] (idDivision, nombre, idDeporte, estado) VALUES (25, 'Segunda División', 110, 'I');
INSERT INTO [dbo].[Division] (idDivision, nombre, idDeporte, estado) VALUES (26, 'Liga Superior Femenina', 111, 'I');
INSERT INTO [dbo].[Division] (idDivision, nombre, idDeporte, estado) VALUES (27, 'Categoría Única', 112, 'I');
INSERT INTO [dbo].[Division] (idDivision, nombre, idDeporte, estado) VALUES (28, 'Liga Central', 113, 'I');
INSERT INTO [dbo].[Division] (idDivision, nombre, idDeporte, estado) VALUES (29, 'Torneo Nacional', 114, 'I');
INSERT INTO [dbo].[Division] (idDivision, nombre, idDeporte, estado) VALUES (30, 'Liga de Honor', 115, 'I');
INSERT INTO [dbo].[Division] (idDivision, nombre, idDeporte, estado) VALUES (31, 'Rango Profesional', 116, 'I');
INSERT INTO [dbo].[Division] (idDivision, nombre, idDeporte, estado) VALUES (32, 'Tour Elite', 117, 'I');
INSERT INTO [dbo].[Division] (idDivision, nombre, idDeporte, estado) VALUES (33, 'Competencia Abierta', 118, 'I');
INSERT INTO [dbo].[Division] (idDivision, nombre, idDeporte, estado) VALUES (34, 'Juvenil Femenino', 119, 'I');
INSERT INTO [dbo].[Division] (idDivision, nombre, idDeporte, estado) VALUES (35, 'Tour Damas', 120, 'I');
INSERT INTO [dbo].[Division] (idDivision, nombre, idDeporte, estado) VALUES (36, 'Nivel 1 (Iniciación)', 121, 'I');
INSERT INTO [dbo].[Division] (idDivision, nombre, idDeporte, estado) VALUES (37, 'Nivel 2 (Avanzado)', 121, 'I');
INSERT INTO [dbo].[Division] (idDivision, nombre, idDeporte, estado) VALUES (38, 'Nivel Elite', 121, 'I');
INSERT INTO [dbo].[Division] (idDivision, nombre, idDeporte, estado) VALUES (39, 'Primera División', 98, 'I');
INSERT INTO [dbo].[Division] (idDivision, nombre, idDeporte, estado) VALUES (40, 'Segunda División', 98, 'I');
INSERT INTO [dbo].[Division] (idDivision, nombre, idDeporte, estado) VALUES (41, 'Tercera División', 98, 'I');
INSERT INTO [dbo].[Division] (idDivision, nombre, idDeporte, estado) VALUES (42, 'Liga Nacional', 99, 'I');
INSERT INTO [dbo].[Division] (idDivision, nombre, idDeporte, estado) VALUES (43, 'Liga de Ascenso', 99, 'I');
INSERT INTO [dbo].[Division] (idDivision, nombre, idDeporte, estado) VALUES (44, 'Categoría A (Pro)', 100, 'I');
INSERT INTO [dbo].[Division] (idDivision, nombre, idDeporte, estado) VALUES (45, 'Categoría B (Amateur)', 100, 'I');
INSERT INTO [dbo].[Division] (idDivision, nombre, idDeporte, estado) VALUES (46, 'Liga Mayor', 101, 'I');
INSERT INTO [dbo].[Division] (idDivision, nombre, idDeporte, estado) VALUES (47, 'Liga Menor', 101, 'I');
INSERT INTO [dbo].[Division] (idDivision, nombre, idDeporte, estado) VALUES (48, 'División de Honor', 102, 'I');
INSERT INTO [dbo].[Division] (idDivision, nombre, idDeporte, estado) VALUES (49, 'Pre-Intermedia', 102, 'I');
INSERT INTO [dbo].[Division] (idDivision, nombre, idDeporte, estado) VALUES (50, 'Serie A1', 103, 'I');
INSERT INTO [dbo].[Division] (idDivision, nombre, idDeporte, estado) VALUES (51, 'Serie A2', 103, 'I');
INSERT INTO [dbo].[Division] (idDivision, nombre, idDeporte, estado) VALUES (52, 'Categoría Profesional', 104, 'I');
INSERT INTO [dbo].[Division] (idDivision, nombre, idDeporte, estado) VALUES (53, 'Categoría Amateur', 104, 'I');
INSERT INTO [dbo].[Division] (idDivision, nombre, idDeporte, estado) VALUES (54, 'Elite', 105, 'I');
INSERT INTO [dbo].[Division] (idDivision, nombre, idDeporte, estado) VALUES (55, 'Sub-23', 105, 'I');
INSERT INTO [dbo].[Division] (idDivision, nombre, idDeporte, estado) VALUES (56, 'División Nacional', 106, 'I');
INSERT INTO [dbo].[Division] (idDivision, nombre, idDeporte, estado) VALUES (57, 'Federados', 107, 'I');
INSERT INTO [dbo].[Division] (idDivision, nombre, idDeporte, estado) VALUES (58, 'Scratch', 108, 'I');
INSERT INTO [dbo].[Division] (idDivision, nombre, idDeporte, estado) VALUES (59, 'Handicap Alto', 108, 'I');
INSERT INTO [dbo].[Division] (idDivision, nombre, idDeporte, estado) VALUES (60, 'Primera Categoría', 109, 'I');
INSERT INTO [dbo].[Division] (idDivision, nombre, idDeporte, estado) VALUES (61, 'Primera División', 110, 'I');
INSERT INTO [dbo].[Division] (idDivision, nombre, idDeporte, estado) VALUES (62, 'Segunda División', 110, 'I');
INSERT INTO [dbo].[Division] (idDivision, nombre, idDeporte, estado) VALUES (63, 'Liga Superior Femenina', 111, 'I');
INSERT INTO [dbo].[Division] (idDivision, nombre, idDeporte, estado) VALUES (64, 'Categoría Única', 112, 'I');
INSERT INTO [dbo].[Division] (idDivision, nombre, idDeporte, estado) VALUES (65, 'Liga Central', 113, 'I');
INSERT INTO [dbo].[Division] (idDivision, nombre, idDeporte, estado) VALUES (66, 'Torneo Nacional', 114, 'I');
INSERT INTO [dbo].[Division] (idDivision, nombre, idDeporte, estado) VALUES (67, 'Liga de Honor', 115, 'I');
INSERT INTO [dbo].[Division] (idDivision, nombre, idDeporte, estado) VALUES (68, 'Rango Profesional', 116, 'I');
INSERT INTO [dbo].[Division] (idDivision, nombre, idDeporte, estado) VALUES (69, 'Tour Elite', 117, 'I');
INSERT INTO [dbo].[Division] (idDivision, nombre, idDeporte, estado) VALUES (70, 'Competencia Abierta', 118, 'I');
INSERT INTO [dbo].[Division] (idDivision, nombre, idDeporte, estado) VALUES (71, 'Juvenil Femenino', 119, 'I');
INSERT INTO [dbo].[Division] (idDivision, nombre, idDeporte, estado) VALUES (72, 'Tour Damas', 120, 'I');
INSERT INTO [dbo].[Division] (idDivision, nombre, idDeporte, estado) VALUES (73, 'Nivel 1 (Iniciación)', 121, 'I');
INSERT INTO [dbo].[Division] (idDivision, nombre, idDeporte, estado) VALUES (74, 'Nivel 2 (Avanzado)', 121, 'I');
INSERT INTO [dbo].[Division] (idDivision, nombre, idDeporte, estado) VALUES (75, 'Nivel Elite', 121, 'I');
INSERT INTO [dbo].[Division] (idDivision, nombre, idDeporte, estado) VALUES (76, 'Primera División', 98, 'A');
INSERT INTO [dbo].[Division] (idDivision, nombre, idDeporte, estado) VALUES (77, 'Segunda División', 98, 'A');
INSERT INTO [dbo].[Division] (idDivision, nombre, idDeporte, estado) VALUES (78, 'Tercera División', 98, 'A');
INSERT INTO [dbo].[Division] (idDivision, nombre, idDeporte, estado) VALUES (79, 'Liga Nacional', 99, 'A');
INSERT INTO [dbo].[Division] (idDivision, nombre, idDeporte, estado) VALUES (80, 'Liga de Ascenso', 99, 'A');
INSERT INTO [dbo].[Division] (idDivision, nombre, idDeporte, estado) VALUES (81, 'Categoría A (Pro)', 100, 'A');
INSERT INTO [dbo].[Division] (idDivision, nombre, idDeporte, estado) VALUES (82, 'Categoría B (Amateur)', 100, 'A');
INSERT INTO [dbo].[Division] (idDivision, nombre, idDeporte, estado) VALUES (83, 'Liga Mayor', 101, 'A');
INSERT INTO [dbo].[Division] (idDivision, nombre, idDeporte, estado) VALUES (84, 'Liga Menor', 101, 'A');
INSERT INTO [dbo].[Division] (idDivision, nombre, idDeporte, estado) VALUES (85, 'División de Honor', 102, 'A');
INSERT INTO [dbo].[Division] (idDivision, nombre, idDeporte, estado) VALUES (86, 'Pre-Intermedia', 102, 'A');
INSERT INTO [dbo].[Division] (idDivision, nombre, idDeporte, estado) VALUES (87, 'Serie A1', 103, 'A');
INSERT INTO [dbo].[Division] (idDivision, nombre, idDeporte, estado) VALUES (88, 'Serie A2', 103, 'A');
INSERT INTO [dbo].[Division] (idDivision, nombre, idDeporte, estado) VALUES (89, 'Categoría Profesional', 104, 'A');
INSERT INTO [dbo].[Division] (idDivision, nombre, idDeporte, estado) VALUES (90, 'Categoría Amateur', 104, 'A');
INSERT INTO [dbo].[Division] (idDivision, nombre, idDeporte, estado) VALUES (91, 'Elite', 105, 'A');
INSERT INTO [dbo].[Division] (idDivision, nombre, idDeporte, estado) VALUES (92, 'Sub-23', 105, 'A');
INSERT INTO [dbo].[Division] (idDivision, nombre, idDeporte, estado) VALUES (93, 'División Nacional', 106, 'A');
INSERT INTO [dbo].[Division] (idDivision, nombre, idDeporte, estado) VALUES (94, 'Federados', 107, 'A');
INSERT INTO [dbo].[Division] (idDivision, nombre, idDeporte, estado) VALUES (95, 'Scratch', 108, 'A');
INSERT INTO [dbo].[Division] (idDivision, nombre, idDeporte, estado) VALUES (96, 'Handicap Alto', 108, 'A');
INSERT INTO [dbo].[Division] (idDivision, nombre, idDeporte, estado) VALUES (97, 'Primera Categoría', 109, 'A');
INSERT INTO [dbo].[Division] (idDivision, nombre, idDeporte, estado) VALUES (98, 'Primera División', 110, 'A');
INSERT INTO [dbo].[Division] (idDivision, nombre, idDeporte, estado) VALUES (99, 'Segunda División', 110, 'A');
INSERT INTO [dbo].[Division] (idDivision, nombre, idDeporte, estado) VALUES (100, 'Liga Superior Femenina', 111, 'A');
INSERT INTO [dbo].[Division] (idDivision, nombre, idDeporte, estado) VALUES (101, 'Categoría Única', 112, 'A');
INSERT INTO [dbo].[Division] (idDivision, nombre, idDeporte, estado) VALUES (102, 'Liga Central', 113, 'A');
INSERT INTO [dbo].[Division] (idDivision, nombre, idDeporte, estado) VALUES (103, 'Torneo Nacional', 114, 'A');
INSERT INTO [dbo].[Division] (idDivision, nombre, idDeporte, estado) VALUES (104, 'Liga de Honor', 115, 'A');
INSERT INTO [dbo].[Division] (idDivision, nombre, idDeporte, estado) VALUES (105, 'Rango Profesional', 116, 'A');
INSERT INTO [dbo].[Division] (idDivision, nombre, idDeporte, estado) VALUES (106, 'Tour Elite', 117, 'A');
INSERT INTO [dbo].[Division] (idDivision, nombre, idDeporte, estado) VALUES (107, 'Competencia Abierta', 118, 'A');
INSERT INTO [dbo].[Division] (idDivision, nombre, idDeporte, estado) VALUES (108, 'Juvenil Femenino', 119, 'A');
INSERT INTO [dbo].[Division] (idDivision, nombre, idDeporte, estado) VALUES (109, 'Tour Damas', 120, 'A');
INSERT INTO [dbo].[Division] (idDivision, nombre, idDeporte, estado) VALUES (110, 'Nivel 1 (Iniciación)', 121, 'A');
INSERT INTO [dbo].[Division] (idDivision, nombre, idDeporte, estado) VALUES (111, 'Nivel 2 (Avanzado)', 121, 'A');
INSERT INTO [dbo].[Division] (idDivision, nombre, idDeporte, estado) VALUES (112, 'Nivel Elite', 121, 'A');
SET IDENTITY_INSERT [dbo].[Division] OFF
GO

SET IDENTITY_INSERT [dbo].[Genero] ON
INSERT INTO [dbo].[Genero] (idGenero, nombre) VALUES (1005, 'Masculino');
INSERT INTO [dbo].[Genero] (idGenero, nombre) VALUES (1006, 'Femenino');
INSERT INTO [dbo].[Genero] (idGenero, nombre) VALUES (1007, 'Otro');
SET IDENTITY_INSERT [dbo].[Genero] OFF
GO

SET IDENTITY_INSERT [dbo].[Pais] ON
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (1, 'Afganistán');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (2, 'Albania');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (3, 'Alemania');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (4, 'Andorra');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (5, 'Angola');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (6, 'Antigua y Barbuda');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (7, 'Arabia Saudita');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (8, 'Argelia');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (9, 'Argentina');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (10, 'Armenia');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (11, 'Australia');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (12, 'Austria');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (13, 'Azerbaiyán');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (14, 'Bahamas');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (15, 'Bangladés');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (16, 'Barbados');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (17, 'Baréin');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (18, 'Bélgica');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (19, 'Belice');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (20, 'Benín');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (21, 'Bielorrusia');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (22, 'Birmania');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (23, 'Bolivia');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (24, 'Bosnia y Herzegovina');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (25, 'Botsuana');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (26, 'Brasil');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (27, 'Brunéi');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (28, 'Bulgaria');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (29, 'Burkina Faso');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (30, 'Burundi');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (31, 'Bután');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (32, 'Cabo Verde');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (33, 'Camboya');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (34, 'Camerún');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (35, 'Canadá');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (36, 'Catar');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (37, 'Chad');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (38, 'Chile');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (39, 'China');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (40, 'Chipre');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (41, 'Ciudad del Vaticano');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (42, 'Colombia');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (43, 'Comoras');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (44, 'Corea del Norte');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (45, 'Corea del Sur');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (46, 'Costa de Marfil');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (47, 'Costa Rica');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (48, 'Croacia');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (49, 'Cuba');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (50, 'Dinamarca');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (51, 'Dominica');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (52, 'Ecuador');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (53, 'Egipto');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (54, 'El Salvador');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (55, 'Emiratos Árabes Unidos');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (56, 'Eritrea');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (57, 'Eslovaquia');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (58, 'Eslovenia');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (59, 'España');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (60, 'Estados Unidos');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (61, 'Estonia');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (62, 'Etiopía');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (63, 'Filipinas');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (64, 'Finlandia');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (65, 'Fiyi');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (66, 'Francia');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (67, 'Gabón');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (68, 'Gambia');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (69, 'Georgia');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (70, 'Ghana');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (71, 'Granada');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (72, 'Grecia');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (73, 'Guatemala');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (74, 'Guyana');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (75, 'Guinea');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (76, 'Guinea ecuatorial');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (77, 'Guinea-Bisáu');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (78, 'Haití');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (79, 'Honduras');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (80, 'Hungría');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (81, 'India');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (82, 'Indonesia');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (83, 'Irak');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (84, 'Irán');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (85, 'Irlanda');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (86, 'Islandia');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (87, 'Islas Marshall');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (88, 'Islas Salomón');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (89, 'Israel');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (90, 'Italia');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (91, 'Jamaica');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (92, 'Japón');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (93, 'Jordania');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (94, 'Kazajistán');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (95, 'Kenia');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (96, 'Kirguistán');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (97, 'Kiribati');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (98, 'Kuwait');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (99, 'Laos');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (100, 'Lesoto');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (101, 'Letonia');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (102, 'Líbano');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (103, 'Liberia');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (104, 'Libia');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (105, 'Liechtenstein');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (106, 'Lituania');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (107, 'Luxemburgo');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (108, 'Macedonia del Norte');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (109, 'Madagascar');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (110, 'Malasia');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (111, 'Malaui');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (112, 'Maldivas');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (113, 'Malí');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (114, 'Malta');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (115, 'Marruecos');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (116, 'Mauricio');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (117, 'Mauritania');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (118, 'México');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (119, 'Micronesia');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (120, 'Moldavia');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (121, 'Mónaco');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (122, 'Mongolia');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (123, 'Montenegro');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (124, 'Mozambique');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (125, 'Namibia');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (126, 'Nauru');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (127, 'Nepal');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (128, 'Nicaragua');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (129, 'Níger');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (130, 'Nigeria');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (131, 'Noruega');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (132, 'Nueva Zelanda');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (133, 'Omán');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (134, 'Países Bajos');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (135, 'Pakistán');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (136, 'Palaos');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (137, 'Panamá');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (138, 'Papúa Nueva Guinea');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (139, 'Paraguay');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (140, 'Perú');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (141, 'Polonia');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (142, 'Portugal');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (143, 'Reino Unido');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (144, 'República Centroafricana');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (145, 'República Checa');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (146, 'República del Congo');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (147, 'República Democrática del Congo');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (148, 'República Dominicana');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (149, 'Ruanda');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (150, 'Rumanía');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (151, 'Rusia');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (152, 'Samoa');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (153, 'San Cristóbal y Nieves');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (154, 'San Marino');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (155, 'San Vicente y las Granadinas');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (156, 'Santa Lucía');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (157, 'Santo Tomé y Príncipe');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (158, 'Senegal');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (159, 'Serbia');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (160, 'Seychelles');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (161, 'Sierra Leona');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (162, 'Singapur');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (163, 'Siria');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (164, 'Somalia');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (165, 'Sri Lanka');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (166, 'Suazilandia');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (167, 'Sudáfrica');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (168, 'Sudán');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (169, 'Sudán del Sur');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (170, 'Suecia');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (171, 'Suiza');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (172, 'Surinam');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (173, 'Tailandia');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (174, 'Tanzania');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (175, 'Tayikistán');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (176, 'Timor Oriental');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (177, 'Togo');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (178, 'Tonga');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (179, 'Trinidad y Tobago');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (180, 'Túnez');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (181, 'Turkmenistán');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (182, 'Turquía');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (183, 'Tuvalu');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (184, 'Ucrania');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (185, 'Uganda');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (186, 'Uruguay');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (187, 'Uzbekistán');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (188, 'Vanuatu');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (189, 'Venezuela');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (190, 'Vietnam');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (191, 'Yemen');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (192, 'Yibuti');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (193, 'Zambia');
INSERT INTO [dbo].[Pais] (idPais, nombre) VALUES (194, 'Zimbabue');
SET IDENTITY_INSERT [dbo].[Pais] OFF
GO

SET IDENTITY_INSERT [dbo].[Liga] ON
INSERT INTO [dbo].[Liga] (idLiga, nombre, idDeporte, idDivision, idPais, foto_perfil, estado) VALUES (3, 'La Liga', 98, 2, 59, 'https://img.com/laliga.png', 'I');
INSERT INTO [dbo].[Liga] (idLiga, nombre, idDeporte, idDivision, idPais, foto_perfil, estado) VALUES (4, 'Segunda División RFEF', 98, 3, 59, 'https://img.com/rfef2.png', 'I');
INSERT INTO [dbo].[Liga] (idLiga, nombre, idDeporte, idDivision, idPais, foto_perfil, estado) VALUES (5, 'Premier League', 98, 2, 143, 'https://img.com/epl.png', 'I');
INSERT INTO [dbo].[Liga] (idLiga, nombre, idDeporte, idDivision, idPais, foto_perfil, estado) VALUES (6, 'Serie A', 98, 2, 90, 'https://img.com/seriea.png', 'I');
INSERT INTO [dbo].[Liga] (idLiga, nombre, idDeporte, idDivision, idPais, foto_perfil, estado) VALUES (7, 'Bundesliga', 98, 2, 3, 'https://img.com/bundes.png', 'I');
INSERT INTO [dbo].[Liga] (idLiga, nombre, idDeporte, idDivision, idPais, foto_perfil, estado) VALUES (8, 'Liga Profesional', 98, 2, 9, 'https://img.com/lpf.png', 'I');
INSERT INTO [dbo].[Liga] (idLiga, nombre, idDeporte, idDivision, idPais, foto_perfil, estado) VALUES (9, 'Brasileirão', 98, 2, 26, 'https://img.com/bra.png', 'I');
INSERT INTO [dbo].[Liga] (idLiga, nombre, idDeporte, idDivision, idPais, foto_perfil, estado) VALUES (10, 'Liga MX', 98, 2, 118, 'https://img.com/mx.png', 'I');
INSERT INTO [dbo].[Liga] (idLiga, nombre, idDeporte, idDivision, idPais, foto_perfil, estado) VALUES (11, 'MLS', 98, 2, 60, 'https://img.com/mls.png', 'I');
INSERT INTO [dbo].[Liga] (idLiga, nombre, idDeporte, idDivision, idPais, foto_perfil, estado) VALUES (12, 'NBA', 99, 5, 60, 'https://img.com/nba.png', 'I');
INSERT INTO [dbo].[Liga] (idLiga, nombre, idDeporte, idDivision, idPais, foto_perfil, estado) VALUES (13, 'G-League', 99, 6, 60, 'https://img.com/gleague.png', 'I');
INSERT INTO [dbo].[Liga] (idLiga, nombre, idDeporte, idDivision, idPais, foto_perfil, estado) VALUES (14, 'Liga ACB', 99, 5, 59, 'https://img.com/acb.png', 'I');
INSERT INTO [dbo].[Liga] (idLiga, nombre, idDeporte, idDivision, idPais, foto_perfil, estado) VALUES (15, 'ATP 1000', 100, 7, 59, 'https://img.com/atp.png', 'I');
INSERT INTO [dbo].[Liga] (idLiga, nombre, idDeporte, idDivision, idPais, foto_perfil, estado) VALUES (16, 'Torneo Regional', 100, 8, 9, 'https://img.com/tennis.png', 'I');
INSERT INTO [dbo].[Liga] (idLiga, nombre, idDeporte, idDivision, idPais, foto_perfil, estado) VALUES (17, 'MLB', 101, 9, 60, 'https://img.com/mlb.png', 'I');
INSERT INTO [dbo].[Liga] (idLiga, nombre, idDeporte, idDivision, idPais, foto_perfil, estado) VALUES (18, 'Triple-A East', 101, 10, 60, 'https://img.com/aaa.png', 'I');
INSERT INTO [dbo].[Liga] (idLiga, nombre, idDeporte, idDivision, idPais, foto_perfil, estado) VALUES (19, 'LIDOM', 101, 9, 148, 'https://img.com/lidom.png', 'I');
INSERT INTO [dbo].[Liga] (idLiga, nombre, idDeporte, idDivision, idPais, foto_perfil, estado) VALUES (20, 'Tour de France', 105, 17, 66, 'https://img.com/tdf.png', 'I');
INSERT INTO [dbo].[Liga] (idLiga, nombre, idDeporte, idDivision, idPais, foto_perfil, estado) VALUES (21, 'Giro d''Italia Sub-23', 105, 18, 90, 'https://img.com/giro.png', 'I');
INSERT INTO [dbo].[Liga] (idLiga, nombre, idDeporte, idDivision, idPais, foto_perfil, estado) VALUES (22, 'Liga F', 110, 24, 59, 'https://img.com/ligaf.png', 'I');
INSERT INTO [dbo].[Liga] (idLiga, nombre, idDeporte, idDivision, idPais, foto_perfil, estado) VALUES (23, 'NWSL', 110, 24, 60, 'https://img.com/nwsl.png', 'I');
INSERT INTO [dbo].[Liga] (idLiga, nombre, idDeporte, idDivision, idPais, foto_perfil, estado) VALUES (24, 'Copa del Mundo Rythmic', 121, 38, 151, 'https://img.com/gim.png', 'I');
INSERT INTO [dbo].[Liga] (idLiga, nombre, idDeporte, idDivision, idPais, foto_perfil, estado) VALUES (25, 'La Liga', 98, 2, 59, 'https://img.com/laliga.png', 'I');
INSERT INTO [dbo].[Liga] (idLiga, nombre, idDeporte, idDivision, idPais, foto_perfil, estado) VALUES (26, 'Segunda División RFEF', 98, 3, 59, 'https://img.com/rfef2.png', 'I');
INSERT INTO [dbo].[Liga] (idLiga, nombre, idDeporte, idDivision, idPais, foto_perfil, estado) VALUES (27, 'Premier League', 98, 2, 143, 'https://img.com/epl.png', 'I');
INSERT INTO [dbo].[Liga] (idLiga, nombre, idDeporte, idDivision, idPais, foto_perfil, estado) VALUES (28, 'Serie A', 98, 2, 90, 'https://img.com/seriea.png', 'I');
INSERT INTO [dbo].[Liga] (idLiga, nombre, idDeporte, idDivision, idPais, foto_perfil, estado) VALUES (29, 'Bundesliga', 98, 2, 3, 'https://img.com/bundes.png', 'I');
INSERT INTO [dbo].[Liga] (idLiga, nombre, idDeporte, idDivision, idPais, foto_perfil, estado) VALUES (30, 'Liga Profesional', 98, 2, 9, 'https://img.com/lpf.png', 'I');
INSERT INTO [dbo].[Liga] (idLiga, nombre, idDeporte, idDivision, idPais, foto_perfil, estado) VALUES (31, 'Brasileirão', 98, 2, 26, 'https://img.com/bra.png', 'I');
INSERT INTO [dbo].[Liga] (idLiga, nombre, idDeporte, idDivision, idPais, foto_perfil, estado) VALUES (32, 'Liga MX', 98, 2, 118, 'https://img.com/mx.png', 'I');
INSERT INTO [dbo].[Liga] (idLiga, nombre, idDeporte, idDivision, idPais, foto_perfil, estado) VALUES (33, 'MLS', 98, 2, 60, 'https://img.com/mls.png', 'I');
INSERT INTO [dbo].[Liga] (idLiga, nombre, idDeporte, idDivision, idPais, foto_perfil, estado) VALUES (34, 'NBA', 99, 5, 60, 'https://img.com/nba.png', 'I');
INSERT INTO [dbo].[Liga] (idLiga, nombre, idDeporte, idDivision, idPais, foto_perfil, estado) VALUES (35, 'G-League', 99, 6, 60, 'https://img.com/gleague.png', 'I');
INSERT INTO [dbo].[Liga] (idLiga, nombre, idDeporte, idDivision, idPais, foto_perfil, estado) VALUES (36, 'Liga ACB', 99, 5, 59, 'https://img.com/acb.png', 'I');
INSERT INTO [dbo].[Liga] (idLiga, nombre, idDeporte, idDivision, idPais, foto_perfil, estado) VALUES (37, 'ATP 1000', 100, 7, 59, 'https://img.com/atp.png', 'I');
INSERT INTO [dbo].[Liga] (idLiga, nombre, idDeporte, idDivision, idPais, foto_perfil, estado) VALUES (38, 'Torneo Regional', 100, 8, 9, 'https://img.com/tennis.png', 'I');
INSERT INTO [dbo].[Liga] (idLiga, nombre, idDeporte, idDivision, idPais, foto_perfil, estado) VALUES (39, 'MLB', 101, 9, 60, 'https://img.com/mlb.png', 'I');
INSERT INTO [dbo].[Liga] (idLiga, nombre, idDeporte, idDivision, idPais, foto_perfil, estado) VALUES (40, 'Triple-A East', 101, 10, 60, 'https://img.com/aaa.png', 'I');
INSERT INTO [dbo].[Liga] (idLiga, nombre, idDeporte, idDivision, idPais, foto_perfil, estado) VALUES (41, 'LIDOM', 101, 9, 148, 'https://img.com/lidom.png', 'I');
INSERT INTO [dbo].[Liga] (idLiga, nombre, idDeporte, idDivision, idPais, foto_perfil, estado) VALUES (42, 'Tour de France', 105, 17, 66, 'https://img.com/tdf.png', 'I');
INSERT INTO [dbo].[Liga] (idLiga, nombre, idDeporte, idDivision, idPais, foto_perfil, estado) VALUES (43, 'Giro d''Italia Sub-23', 105, 18, 90, 'https://img.com/giro.png', 'I');
INSERT INTO [dbo].[Liga] (idLiga, nombre, idDeporte, idDivision, idPais, foto_perfil, estado) VALUES (44, 'Liga F', 110, 24, 59, 'https://img.com/ligaf.png', 'I');
INSERT INTO [dbo].[Liga] (idLiga, nombre, idDeporte, idDivision, idPais, foto_perfil, estado) VALUES (45, 'NWSL', 110, 24, 60, 'https://img.com/nwsl.png', 'I');
INSERT INTO [dbo].[Liga] (idLiga, nombre, idDeporte, idDivision, idPais, foto_perfil, estado) VALUES (46, 'Copa del Mundo Rythmic', 121, 38, 151, 'https://img.com/gim.png', 'I');
INSERT INTO [dbo].[Liga] (idLiga, nombre, idDeporte, idDivision, idPais, foto_perfil, estado) VALUES (47, 'La Liga', 98, 2, 59, 'https://img.com/laliga.png', 'I');
INSERT INTO [dbo].[Liga] (idLiga, nombre, idDeporte, idDivision, idPais, foto_perfil, estado) VALUES (48, 'Segunda División RFEF', 98, 3, 59, 'https://img.com/rfef2.png', 'I');
INSERT INTO [dbo].[Liga] (idLiga, nombre, idDeporte, idDivision, idPais, foto_perfil, estado) VALUES (49, 'Premier League', 98, 2, 143, 'https://img.com/epl.png', 'I');
INSERT INTO [dbo].[Liga] (idLiga, nombre, idDeporte, idDivision, idPais, foto_perfil, estado) VALUES (50, 'Serie A', 98, 2, 90, 'https://img.com/seriea.png', 'I');
INSERT INTO [dbo].[Liga] (idLiga, nombre, idDeporte, idDivision, idPais, foto_perfil, estado) VALUES (51, 'Bundesliga', 98, 2, 3, 'https://img.com/bundes.png', 'I');
INSERT INTO [dbo].[Liga] (idLiga, nombre, idDeporte, idDivision, idPais, foto_perfil, estado) VALUES (52, 'Liga Profesional', 98, 2, 9, 'https://img.com/lpf.png', 'I');
INSERT INTO [dbo].[Liga] (idLiga, nombre, idDeporte, idDivision, idPais, foto_perfil, estado) VALUES (53, 'Brasileirão', 98, 2, 26, 'https://img.com/bra.png', 'I');
INSERT INTO [dbo].[Liga] (idLiga, nombre, idDeporte, idDivision, idPais, foto_perfil, estado) VALUES (54, 'Liga MX', 98, 2, 118, 'https://img.com/mx.png', 'I');
INSERT INTO [dbo].[Liga] (idLiga, nombre, idDeporte, idDivision, idPais, foto_perfil, estado) VALUES (55, 'MLS', 98, 2, 60, 'https://img.com/mls.png', 'I');
INSERT INTO [dbo].[Liga] (idLiga, nombre, idDeporte, idDivision, idPais, foto_perfil, estado) VALUES (56, 'NBA', 99, 5, 60, 'https://img.com/nba.png', 'I');
INSERT INTO [dbo].[Liga] (idLiga, nombre, idDeporte, idDivision, idPais, foto_perfil, estado) VALUES (57, 'G-League', 99, 6, 60, 'https://img.com/gleague.png', 'I');
INSERT INTO [dbo].[Liga] (idLiga, nombre, idDeporte, idDivision, idPais, foto_perfil, estado) VALUES (58, 'Liga ACB', 99, 5, 59, 'https://img.com/acb.png', 'I');
INSERT INTO [dbo].[Liga] (idLiga, nombre, idDeporte, idDivision, idPais, foto_perfil, estado) VALUES (59, 'ATP 1000', 100, 7, 59, 'https://img.com/atp.png', 'I');
INSERT INTO [dbo].[Liga] (idLiga, nombre, idDeporte, idDivision, idPais, foto_perfil, estado) VALUES (60, 'Torneo Regional', 100, 8, 9, 'https://img.com/tennis.png', 'I');
INSERT INTO [dbo].[Liga] (idLiga, nombre, idDeporte, idDivision, idPais, foto_perfil, estado) VALUES (61, 'MLB', 101, 9, 60, 'https://img.com/mlb.png', 'I');
INSERT INTO [dbo].[Liga] (idLiga, nombre, idDeporte, idDivision, idPais, foto_perfil, estado) VALUES (62, 'Triple-A East', 101, 10, 60, 'https://img.com/aaa.png', 'I');
INSERT INTO [dbo].[Liga] (idLiga, nombre, idDeporte, idDivision, idPais, foto_perfil, estado) VALUES (63, 'LIDOM', 101, 9, 148, 'https://img.com/lidom.png', 'I');
INSERT INTO [dbo].[Liga] (idLiga, nombre, idDeporte, idDivision, idPais, foto_perfil, estado) VALUES (64, 'Tour de France', 105, 17, 66, 'https://img.com/tdf.png', 'I');
INSERT INTO [dbo].[Liga] (idLiga, nombre, idDeporte, idDivision, idPais, foto_perfil, estado) VALUES (65, 'Giro d''Italia Sub-23', 105, 18, 90, 'https://img.com/giro.png', 'I');
INSERT INTO [dbo].[Liga] (idLiga, nombre, idDeporte, idDivision, idPais, foto_perfil, estado) VALUES (66, 'Liga F', 110, 24, 59, 'https://img.com/ligaf.png', 'I');
INSERT INTO [dbo].[Liga] (idLiga, nombre, idDeporte, idDivision, idPais, foto_perfil, estado) VALUES (67, 'NWSL', 110, 24, 60, 'https://img.com/nwsl.png', 'I');
INSERT INTO [dbo].[Liga] (idLiga, nombre, idDeporte, idDivision, idPais, foto_perfil, estado) VALUES (68, 'Copa del Mundo Rythmic', 121, 38, 151, 'https://img.com/gim.png', 'I');
INSERT INTO [dbo].[Liga] (idLiga, nombre, idDeporte, idDivision, idPais, foto_perfil, estado) VALUES (69, 'La Liga', 98, 76, 59, 'https://img.com/laliga.png', 'A');
INSERT INTO [dbo].[Liga] (idLiga, nombre, idDeporte, idDivision, idPais, foto_perfil, estado) VALUES (70, 'Segunda División RFEF', 98, 77, 59, 'https://img.com/rfef2.png', 'A');
INSERT INTO [dbo].[Liga] (idLiga, nombre, idDeporte, idDivision, idPais, foto_perfil, estado) VALUES (71, 'Premier League', 98, 76, 143, 'https://img.com/epl.png', 'A');
INSERT INTO [dbo].[Liga] (idLiga, nombre, idDeporte, idDivision, idPais, foto_perfil, estado) VALUES (72, 'Serie A', 98, 76, 90, 'https://img.com/seriea.png', 'A');
INSERT INTO [dbo].[Liga] (idLiga, nombre, idDeporte, idDivision, idPais, foto_perfil, estado) VALUES (73, 'Bundesliga', 98, 76, 3, 'https://img.com/bundes.png', 'A');
INSERT INTO [dbo].[Liga] (idLiga, nombre, idDeporte, idDivision, idPais, foto_perfil, estado) VALUES (74, 'Liga Profesional', 98, 76, 9, 'https://img.com/lpf.png', 'A');
INSERT INTO [dbo].[Liga] (idLiga, nombre, idDeporte, idDivision, idPais, foto_perfil, estado) VALUES (75, 'Brasileirão', 98, 76, 26, 'https://img.com/bra.png', 'A');
INSERT INTO [dbo].[Liga] (idLiga, nombre, idDeporte, idDivision, idPais, foto_perfil, estado) VALUES (76, 'Liga MX', 98, 76, 118, 'https://img.com/mx.png', 'A');
INSERT INTO [dbo].[Liga] (idLiga, nombre, idDeporte, idDivision, idPais, foto_perfil, estado) VALUES (77, 'MLS', 98, 76, 60, 'https://img.com/mls.png', 'A');
INSERT INTO [dbo].[Liga] (idLiga, nombre, idDeporte, idDivision, idPais, foto_perfil, estado) VALUES (78, 'NBA', 99, 79, 60, 'https://img.com/nba.png', 'A');
INSERT INTO [dbo].[Liga] (idLiga, nombre, idDeporte, idDivision, idPais, foto_perfil, estado) VALUES (79, 'G-League', 99, 80, 60, 'https://img.com/gleague.png', 'A');
INSERT INTO [dbo].[Liga] (idLiga, nombre, idDeporte, idDivision, idPais, foto_perfil, estado) VALUES (80, 'Liga ACB', 99, 79, 59, 'https://img.com/acb.png', 'A');
INSERT INTO [dbo].[Liga] (idLiga, nombre, idDeporte, idDivision, idPais, foto_perfil, estado) VALUES (81, 'ATP 1000', 100, 81, 59, 'https://img.com/atp.png', 'A');
INSERT INTO [dbo].[Liga] (idLiga, nombre, idDeporte, idDivision, idPais, foto_perfil, estado) VALUES (82, 'Torneo Regional', 100, 82, 9, 'https://img.com/tennis.png', 'A');
INSERT INTO [dbo].[Liga] (idLiga, nombre, idDeporte, idDivision, idPais, foto_perfil, estado) VALUES (83, 'MLB', 101, 83, 60, 'https://img.com/mlb.png', 'A');
INSERT INTO [dbo].[Liga] (idLiga, nombre, idDeporte, idDivision, idPais, foto_perfil, estado) VALUES (84, 'Triple-A East', 101, 84, 60, 'https://img.com/aaa.png', 'A');
INSERT INTO [dbo].[Liga] (idLiga, nombre, idDeporte, idDivision, idPais, foto_perfil, estado) VALUES (85, 'LIDOM', 101, 83, 148, 'https://img.com/lidom.png', 'A');
INSERT INTO [dbo].[Liga] (idLiga, nombre, idDeporte, idDivision, idPais, foto_perfil, estado) VALUES (86, 'Tour de France', 105, 91, 66, 'https://img.com/tdf.png', 'A');
INSERT INTO [dbo].[Liga] (idLiga, nombre, idDeporte, idDivision, idPais, foto_perfil, estado) VALUES (87, 'Giro d''Italia Sub-23', 105, 92, 90, 'https://img.com/giro.png', 'A');
INSERT INTO [dbo].[Liga] (idLiga, nombre, idDeporte, idDivision, idPais, foto_perfil, estado) VALUES (88, 'Liga F', 110, 98, 59, 'https://img.com/ligaf.png', 'A');
INSERT INTO [dbo].[Liga] (idLiga, nombre, idDeporte, idDivision, idPais, foto_perfil, estado) VALUES (89, 'NWSL', 110, 98, 60, 'https://img.com/nwsl.png', 'A');
INSERT INTO [dbo].[Liga] (idLiga, nombre, idDeporte, idDivision, idPais, foto_perfil, estado) VALUES (90, 'Copa del Mundo Rythmic', 121, 112, 151, 'https://img.com/gim.png', 'A');
SET IDENTITY_INSERT [dbo].[Liga] OFF
GO

SET IDENTITY_INSERT [dbo].[Temporada] ON
INSERT INTO [dbo].[Temporada] (idTemporada, fecha_inicio, fecha_fin, idDeporte) VALUES (1, '2025-08-15', '2026-05-30', 98);
INSERT INTO [dbo].[Temporada] (idTemporada, fecha_inicio, fecha_fin, idDeporte) VALUES (2, '2025-10-20', '2026-06-15', 99);
INSERT INTO [dbo].[Temporada] (idTemporada, fecha_inicio, fecha_fin, idDeporte) VALUES (3, '2025-09-01', '2026-05-20', 103);
INSERT INTO [dbo].[Temporada] (idTemporada, fecha_inicio, fecha_fin, idDeporte) VALUES (4, '2025-08-20', '2026-05-25', 110);
INSERT INTO [dbo].[Temporada] (idTemporada, fecha_inicio, fecha_fin, idDeporte) VALUES (5, '2025-10-01', '2026-05-15', 111);
INSERT INTO [dbo].[Temporada] (idTemporada, fecha_inicio, fecha_fin, idDeporte) VALUES (6, '2025-09-15', '2026-05-10', 115);
INSERT INTO [dbo].[Temporada] (idTemporada, fecha_inicio, fecha_fin, idDeporte) VALUES (7, '2025-10-15', '2026-04-30', 109);
INSERT INTO [dbo].[Temporada] (idTemporada, fecha_inicio, fecha_fin, idDeporte) VALUES (8, '2026-01-01', '2026-11-20', 100);
INSERT INTO [dbo].[Temporada] (idTemporada, fecha_inicio, fecha_fin, idDeporte) VALUES (9, '2026-03-25', '2026-10-30', 101);
INSERT INTO [dbo].[Temporada] (idTemporada, fecha_inicio, fecha_fin, idDeporte) VALUES (10, '2026-02-01', '2026-11-15', 102);
INSERT INTO [dbo].[Temporada] (idTemporada, fecha_inicio, fecha_fin, idDeporte) VALUES (11, '2026-01-15', '2026-12-15', 104);
INSERT INTO [dbo].[Temporada] (idTemporada, fecha_inicio, fecha_fin, idDeporte) VALUES (12, '2026-01-01', '2026-10-31', 105);
INSERT INTO [dbo].[Temporada] (idTemporada, fecha_inicio, fecha_fin, idDeporte) VALUES (13, '2026-01-01', '2026-12-31', 106);
INSERT INTO [dbo].[Temporada] (idTemporada, fecha_inicio, fecha_fin, idDeporte) VALUES (14, '2026-01-01', '2026-12-31', 107);
INSERT INTO [dbo].[Temporada] (idTemporada, fecha_inicio, fecha_fin, idDeporte) VALUES (15, '2026-01-05', '2026-12-10', 108);
INSERT INTO [dbo].[Temporada] (idTemporada, fecha_inicio, fecha_fin, idDeporte) VALUES (16, '2026-01-01', '2026-11-30', 112);
INSERT INTO [dbo].[Temporada] (idTemporada, fecha_inicio, fecha_fin, idDeporte) VALUES (17, '2026-04-01', '2026-09-30', 113);
INSERT INTO [dbo].[Temporada] (idTemporada, fecha_inicio, fecha_fin, idDeporte) VALUES (18, '2026-02-15', '2026-11-01', 114);
INSERT INTO [dbo].[Temporada] (idTemporada, fecha_inicio, fecha_fin, idDeporte) VALUES (19, '2026-01-15', '2026-12-15', 116);
INSERT INTO [dbo].[Temporada] (idTemporada, fecha_inicio, fecha_fin, idDeporte) VALUES (20, '2026-02-01', '2026-10-15', 117);
INSERT INTO [dbo].[Temporada] (idTemporada, fecha_inicio, fecha_fin, idDeporte) VALUES (21, '2026-01-01', '2026-12-31', 118);
INSERT INTO [dbo].[Temporada] (idTemporada, fecha_inicio, fecha_fin, idDeporte) VALUES (22, '2026-01-01', '2026-12-31', 119);
INSERT INTO [dbo].[Temporada] (idTemporada, fecha_inicio, fecha_fin, idDeporte) VALUES (23, '2026-01-10', '2026-12-05', 120);
INSERT INTO [dbo].[Temporada] (idTemporada, fecha_inicio, fecha_fin, idDeporte) VALUES (24, '2026-01-01', '2026-12-15', 121);
INSERT INTO [dbo].[Temporada] (idTemporada, fecha_inicio, fecha_fin, idDeporte) VALUES (25, '2025-08-15', '2026-05-30', 98);
INSERT INTO [dbo].[Temporada] (idTemporada, fecha_inicio, fecha_fin, idDeporte) VALUES (26, '2025-10-20', '2026-06-15', 99);
INSERT INTO [dbo].[Temporada] (idTemporada, fecha_inicio, fecha_fin, idDeporte) VALUES (27, '2025-09-01', '2026-05-20', 103);
INSERT INTO [dbo].[Temporada] (idTemporada, fecha_inicio, fecha_fin, idDeporte) VALUES (28, '2025-08-20', '2026-05-25', 110);
INSERT INTO [dbo].[Temporada] (idTemporada, fecha_inicio, fecha_fin, idDeporte) VALUES (29, '2025-10-01', '2026-05-15', 111);
INSERT INTO [dbo].[Temporada] (idTemporada, fecha_inicio, fecha_fin, idDeporte) VALUES (30, '2025-09-15', '2026-05-10', 115);
INSERT INTO [dbo].[Temporada] (idTemporada, fecha_inicio, fecha_fin, idDeporte) VALUES (31, '2025-10-15', '2026-04-30', 109);
INSERT INTO [dbo].[Temporada] (idTemporada, fecha_inicio, fecha_fin, idDeporte) VALUES (32, '2026-01-01', '2026-11-20', 100);
INSERT INTO [dbo].[Temporada] (idTemporada, fecha_inicio, fecha_fin, idDeporte) VALUES (33, '2026-03-25', '2026-10-30', 101);
INSERT INTO [dbo].[Temporada] (idTemporada, fecha_inicio, fecha_fin, idDeporte) VALUES (34, '2026-02-01', '2026-11-15', 102);
INSERT INTO [dbo].[Temporada] (idTemporada, fecha_inicio, fecha_fin, idDeporte) VALUES (35, '2026-01-15', '2026-12-15', 104);
INSERT INTO [dbo].[Temporada] (idTemporada, fecha_inicio, fecha_fin, idDeporte) VALUES (36, '2026-01-01', '2026-10-31', 105);
INSERT INTO [dbo].[Temporada] (idTemporada, fecha_inicio, fecha_fin, idDeporte) VALUES (37, '2026-01-01', '2026-12-31', 106);
INSERT INTO [dbo].[Temporada] (idTemporada, fecha_inicio, fecha_fin, idDeporte) VALUES (38, '2026-01-01', '2026-12-31', 107);
INSERT INTO [dbo].[Temporada] (idTemporada, fecha_inicio, fecha_fin, idDeporte) VALUES (39, '2026-01-05', '2026-12-10', 108);
INSERT INTO [dbo].[Temporada] (idTemporada, fecha_inicio, fecha_fin, idDeporte) VALUES (40, '2026-01-01', '2026-11-30', 112);
INSERT INTO [dbo].[Temporada] (idTemporada, fecha_inicio, fecha_fin, idDeporte) VALUES (41, '2026-04-01', '2026-09-30', 113);
INSERT INTO [dbo].[Temporada] (idTemporada, fecha_inicio, fecha_fin, idDeporte) VALUES (42, '2026-02-15', '2026-11-01', 114);
INSERT INTO [dbo].[Temporada] (idTemporada, fecha_inicio, fecha_fin, idDeporte) VALUES (43, '2026-01-15', '2026-12-15', 116);
INSERT INTO [dbo].[Temporada] (idTemporada, fecha_inicio, fecha_fin, idDeporte) VALUES (44, '2026-02-01', '2026-10-15', 117);
INSERT INTO [dbo].[Temporada] (idTemporada, fecha_inicio, fecha_fin, idDeporte) VALUES (45, '2026-01-01', '2026-12-31', 118);
INSERT INTO [dbo].[Temporada] (idTemporada, fecha_inicio, fecha_fin, idDeporte) VALUES (46, '2026-01-01', '2026-12-31', 119);
INSERT INTO [dbo].[Temporada] (idTemporada, fecha_inicio, fecha_fin, idDeporte) VALUES (47, '2026-01-10', '2026-12-05', 120);
INSERT INTO [dbo].[Temporada] (idTemporada, fecha_inicio, fecha_fin, idDeporte) VALUES (48, '2026-01-01', '2026-12-15', 121);
SET IDENTITY_INSERT [dbo].[Temporada] OFF
GO

SET IDENTITY_INSERT [dbo].[Persona] ON
INSERT INTO [dbo].[Persona] (idPersona, pnombre, snombre, papellido, sapellido, dni, idGenero, direccion, idPais, edad) VALUES (6, 'angel', 'gabriel', 'zavala', 'padilla', '20201900397', 1005, 'comayagua', 79, 23);
INSERT INTO [dbo].[Persona] (idPersona, pnombre, snombre, papellido, sapellido, dni, idGenero, direccion, idPais, edad) VALUES (8, 'PEDRO', 'MANUEL', 'GARCIA', 'PADILLA', '20201900398', 1005, 'tegucigalpa', 79, 23);
INSERT INTO [dbo].[Persona] (idPersona, pnombre, snombre, papellido, sapellido, dni, idGenero, direccion, idPais, edad) VALUES (9, 'PEDRO', 'GABRIEL', 'ZAVALA', 'PA', '20201900399', 1005, 'comayagua', 3, 20);
INSERT INTO [dbo].[Persona] (idPersona, pnombre, snombre, papellido, sapellido, dni, idGenero, direccion, idPais, edad) VALUES (10, 'PEDRO', 'GABRIEL', 'ZAVALA', 'PADILLA', '20201900400', 1005, 'comayagua', 3, 20);
INSERT INTO [dbo].[Persona] (idPersona, pnombre, snombre, papellido, sapellido, dni, idGenero, direccion, idPais, edad) VALUES (1010, 'ANGEL', 'GABRIEL', 'ZAVALA', 'PADILLA', '20201900402', 1005, 'comayagua', 9, 20);
INSERT INTO [dbo].[Persona] (idPersona, pnombre, snombre, papellido, sapellido, dni, idGenero, direccion, idPais, edad) VALUES (1011, 'ANGEL', 'GABRIEL', 'ZAVALA', 'PADILLA', '20201900403', 1005, 'comayagua', 79, 23);
INSERT INTO [dbo].[Persona] (idPersona, pnombre, snombre, papellido, sapellido, dni, idGenero, direccion, idPais, edad) VALUES (1012, 'ANGEL', 'GABRIEL', 'ZAVALA', 'PADILLA', '20201900404', 1005, 'comayagua', 79, 23);
SET IDENTITY_INSERT [dbo].[Persona] OFF
GO

SET IDENTITY_INSERT [dbo].[Usuario] ON
INSERT INTO [dbo].[Usuario] (idUsuario, correo, password, idPersona, rol, foto_perfil, estado, fecha_hora_registro) VALUES (6, 'prueba10@gmail.com', 'Anzp12345@', 6, 'AFIC', NULL, 'A', '2026-04-02 05:57:05.773');
INSERT INTO [dbo].[Usuario] (idUsuario, correo, password, idPersona, rol, foto_perfil, estado, fecha_hora_registro) VALUES (7, 'prueba11@gmail.com', '$2b$10$y3rfgbWTpbXiLSjYh4sPGO1K3WEq6XiwadFPSi7HuFGLVk9vhSYci', 8, 'AFIC', NULL, 'A', '2026-04-02 06:33:51.590');
INSERT INTO [dbo].[Usuario] (idUsuario, correo, password, idPersona, rol, foto_perfil, estado, fecha_hora_registro) VALUES (8, 'prueba12@gmail.com', '$2b$10$tUH3NVuCOzXwZftmZZuKku9u7tSnL7lgPH/a2oXDU6Ef68mJJSoh.', 9, 'AFIC', NULL, 'A', '2026-04-02 19:35:11.653');
INSERT INTO [dbo].[Usuario] (idUsuario, correo, password, idPersona, rol, foto_perfil, estado, fecha_hora_registro) VALUES (9, 'prueba13@gmail.com', '$2b$10$9sEu4TYQxg37MdGmEODyQ.zp44g.mw9oQHSU7qDje1hz1jslBq992', 10, 'AFIC', NULL, 'A', '2026-04-02 19:38:57.957');
INSERT INTO [dbo].[Usuario] (idUsuario, correo, password, idPersona, rol, foto_perfil, estado, fecha_hora_registro) VALUES (1009, 'prueba14@gmail.com', '$2b$10$jrwYFMZAilaASCxceD84Hu0QbOOLHlJx9tzhMO7Op21feZFz9feem', 1010, 'AFIC', NULL, 'A', '2026-04-09 10:47:01.610');
INSERT INTO [dbo].[Usuario] (idUsuario, correo, password, idPersona, rol, foto_perfil, estado, fecha_hora_registro) VALUES (1010, 'prueba15@gmail.com', '$2b$10$Sjx2XIQGjBwfpOTn8GpZ0OZqVo3gyalBUazjpLS3Y9KLPROnW9f5W', 1011, 'AFIC', NULL, 'A', '2026-04-12 04:23:03.707');
INSERT INTO [dbo].[Usuario] (idUsuario, correo, password, idPersona, rol, foto_perfil, estado, fecha_hora_registro) VALUES (1011, 'prueba16@gmail.com', '$2b$10$usVXRYfwt1Ix4RU9SmOajuVev3xrd7AJ07y7ShQQHkEiC6oJ96UfO', 1012, 'AFIC', NULL, 'A', '2026-04-12 04:42:52.847');
SET IDENTITY_INSERT [dbo].[Usuario] OFF
GO

SET IDENTITY_INSERT [dbo].[Telefono] ON
INSERT INTO [dbo].[Telefono] (idTelefono, numero, idPersona) VALUES (1, '89276160', 6);
INSERT INTO [dbo].[Telefono] (idTelefono, numero, idPersona) VALUES (2, '85236941', 1010);
INSERT INTO [dbo].[Telefono] (idTelefono, numero, idPersona) VALUES (3, '89276565', 1011);
INSERT INTO [dbo].[Telefono] (idTelefono, numero, idPersona) VALUES (4, '86956312', 1012);
SET IDENTITY_INSERT [dbo].[Telefono] OFF
GO
